time-server: 
  image: ifilyaninitmo/time-server-mega-itmo:main
  port: 8001
  env: 
    - name: MONGODB_CONN_STR
      value: "mongodb://newAdmin:password@127.0.0.1:27017"
    - name: TIMESERVER_URL
      value: "http://time-server:8001"

auth-server: 
  image: ifilyaninitmo/auth-server-mega-itmo:main
  port: 8000
  env: 
    - name: MONGODB_CONN_STR
      value: "mongodb://newAdmin:password@127.0.0.1:27017"
    - name: TIMESERVER_URL
      value: "http://time-server:8001"
